exclude: "docs|node_modules|migrations|.git|.tox"
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    stages: [push]
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
    name: formatting code
    description: hook formats python code to look nice
